name: Cypress testes pipeline

on: [push]

jobs:
  cypress-electron-tests:
    runs-on: ubunto-latest
    steps:
     - name: Get Code
       uses: actions/checkout@v4.1.7

     - name: Install Depedencies
       run: npm install

     - name: Run end2end Tests
       run: npx cypress run
      

