name: Cypress testes pipeline

on: 
  workflow_dispatch:
    inputs:
      cli:
        description: Run by cypress command line
        default: yarn cypress run

jobs:
  cypress-electron-tests:
   runs-on: ubuntu-latest
   container:
    image: cypress/browsers:node18.12.0-chrome103-ff107
    options: --user 1001
   steps:
     - name: Get Code
       uses: actions/checkout@v4.1.7

     - name: Install Depedencies
       run: npm install

     - name: Run end2end Tests
       run: ${{ github.event.inputs.cli }}
  cypress-chrome-tests:
    needs: cypress-electron-tests
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node18.12.0-chrome103-ff107
      options: --user 1001
    steps:
     - name: Get Code
       uses: actions/checkout@v4.1.7

     - name: Install Depedencies
       run: npm install

     - name: Run end2end Tests
       run: ${{ github.event.inputs.cli }}
  cypress-firefox-tests:
    needs: cypress-chrome-tests
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node18.12.0-chrome103-ff107
      options: --user 1001
    steps:
     - name: Get Code
       uses: actions/checkout@v4.1.7

     - name: Install Depedencies
       run: npm install

     - name: Run end2end Tests
       run: ${{ github.event.inputs.cli }}
  cypress-edge-tests:
    needs: cypress-firefox-tests
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node18.12.0-chrome103-ff107
      options: --user 1001
    steps:
     - name: Get Code
       uses: actions/checkout@v4.1.7

     - name: Install Depedencies
       run: npm install

     - name: Run end2end Tests
       run: ${{ github.event.inputs.cli }}
      

